#!/usr/bin/env sh
echo "start"
IDFILE="/tmp/i3_master_id.txt"
if [ ! -f "${IDFILE}" ]
then
    touch "$IDFILE"
fi
echo " Kill id" | cat $IDFILE
kill $(cat "$IDFILE")
DIR=`dirname $0`
# python3 ./i3-swallow.py & echo $! > id.txt 
python3 $DIR/i3_master_layout.py --debug & echo $! > $IDFILE 

